apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            - name: bootstrap.memory_lock
              value: "true"
          image: thr3a/growi-es
          name: elasticsearch
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: elasticsearch-hostpath1
              subPath: elasticsearch.yml
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: es
          name: es-data
        - configMap:
            name: es-conf
          name: elasticsearch-hostpath1
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 3000
