apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:8.0.0
          name: mongo
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-configdb
            - mountPath: /data/db
              name: mongo-db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: growiuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mUHw32hTTEaZ
            - name: MONGO_INITDB_DATABASE
              value: growi
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: db-config
          name: mongo-configdb
        - persistentVolumeClaim:
            claimName: db-data
          name: mongo-db
