apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:8.0.0
          name: mongo
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-configdb
            - mountPath: /data/db
              name: mongo-db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: growiuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mUHw32hTTEaZ
            - name: MONGO_INITDB_DATABASE
              value: growi
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: db-config
          name: mongo-configdb
        - persistentVolumeClaim:
            claimName: db-data
          name: mongo-db
---
# mongodb-express
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mongodb-express
  name: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-express
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mongodb-express
    spec:
      containers:
        - image: mongo-express:1.0.0
          name: mongodb-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: growiuser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: mUHw32hTTEaZ
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: adminpassword
      restartPolicy: Always
---
# mongodb-express Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s/overlays/local
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mongodb-express
  name: mongodb-express
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  ipFamilyPolicy: PreferDualStack
  selector:
    io.kompose.service: mongodb-express
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-express-ingress
spec:
  rules:
    - host: mongo-dev.uniproject.jp
      http:
        paths:
          - backend:
              service:
                name: mongodb-express
                port:
                  number: 8081
            path: /
            pathType: Prefix
